### ISSUE TITLE
add new entry error

### ISSUE THREAD

**Issue by st4nny** [MuhammadWahajTaseer/JSWikiGanttFrontEnd#1]
hi, when i submit a new entry i have this error:

JSWikiGanttFrontEnd.js?1&303:1024 Uncaught TypeError: moment_instance.businessAdd is not a function
    at Object.oJSWikiGanttFrontEnd.oModTask.addBusinessDays (JSWikiGanttFrontEnd.js?1&303:1024)
    at Object.oJSWikiGanttFrontEnd.oModTask.preSubmitTask (JSWikiGanttFrontEnd.js?1&303:712)
    at Object.oJSWikiGanttFrontEnd.oModTask.submitAdd (JSWikiGanttFrontEnd.js?1&303:536)
    at HTMLInputElement.eval (eval at sftJSmsg.show (sftJSmsg.js?1&303:384), <anonymous>:2:31)
oJSWikiGanttFrontEnd.oModTask.addBusinessDays @ JSWikiGanttFrontEnd.js?1&303:1024
oJSWikiGanttFrontEnd.oModTask.preSubmitTask @ JSWikiGanttFrontEnd.js?1&303:712
oJSWikiGanttFrontEnd.oModTask.submitAdd @ JSWikiGanttFrontEnd.js?1&303:536
(anonymous) @ VM1377:2

the new moment object, moment_instance, is created but the method businessAdd is not loaded

**Comment by Wahaj10** [comment]
Hey, I think that probably means this script wasn't loaded: 
$wgOut->addScriptFile(LoadJS::getCSSJSLink("**lib/node_modules/moment-business-days/index.js**"));
Could you please 'inspect element' and check the debugger tab to see if it was loaded?

**Comment by Wahaj10** [comment]
Also could you please provide more information about the environment.. Like mediawiki version?

**Comment by st4nny** [comment]
Yes it was loaded. 
MediaWiki version:1.28

in my LocalSettings.php i load the extensions in this way
`require_once "$IP/extensions/JSWikiGantt/JSWikiGantt.php";
wfLoadExtension('JSWikiGanttFrontEnd');`

**Comment by st4nny** [comment]
In my console i have this warning message:
`load.php?debug=false&lang=it&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1anq05z:154 Use of "Map-values" is deprecated. mw.Map#values is deprecated. Use mw.Map#get() instead.
get @ load.php?debug=false&lang=it&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1anq05z:154
window.onload @ JSWikiGanttFrontEnd.js?1&303:14`

**Comment by st4nny** [comment]
i use chromium v62, same errore on Firefox 56.0

**Comment by Wahaj10** [comment]
I just updated firefox to 56, but I can't seem to re-create the issue, I will try with mediawiki version 1.28, my current mediawiki version is 1.29

**Comment by Wahaj10** [comment]
I also tried it on mediawiki version 1.28 with firefox version 56, and it seems to be working fine for me...

**Comment by Wahaj10** [comment]
So the issue is that it can't recognize the function businessAdd.. I'll add a work around for it: **If it can't use the businessAdd function then it'll add month days (not taking into account the weekends...)**  Please re download the code from the repository and let me know if it works!

**Comment by st4nny** [comment]
Perfect! Great Work MuhammadWahajTaseer!

**Comment by Wahaj10** [comment]
Call me Wahaj, thanks. I hope you fine the extension useful!

**Comment by st4nny** [comment]
Great extension! Bye bye Wahaj
